GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/100

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Bob Smith",
  "number": "111-111-1111"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Eve Smith"
}

### Create duplicate entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Anna",
  "number": "111-111-111"
}


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Bob Smith",
  "number": "111-111-1111"
}